production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    min_memory: 512m
    max_memory: 640m


development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    min_memory: 512m
    max_memory: 640m

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
