#!/usr/bin/env ruby
ENV['RAILS_ENV'] ||= 'production'
require File.expand_path(File.dirname(__FILE__) + "/../config/environment")
require 'rubygems'
require 'daemons'

SHARED_DIR = "tmp"

Daemons.run_proc('monitor_solr', :dir_mode => :normal, :dir => "#{SHARED_DIR}/pids", :log_output => true) do
  begin
    SolrMonitor.start
  rescue SignalException
    # why this does not work?
  end
end

